### ISSUE TITLE
Request to Remove SimpleLogin domains from your Disposable Domains list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [fnando/email_data#21]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. To be more precise, dralias.com, 8alias.com, as well as simplelogin.fr are included.

At Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list. Can you elaborate why these domains are incorporated? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

Have a pleasant day.

**Comment by fnando** [comment]
domains have been added to the list of private relays, which removes them from the disposable domain list.

https://github.com/fnando/email_data/blob/main/data/manual/private_relays.txt
